In [8]:
from random import random
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue

import numpy as np

In [24]:
PROBLEM_SIZE = 500
NUM_SETS = 10_000
SETS = tuple(
    np.array([random() < 0.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS)
)
State = namedtuple('State', ['taken', 'not_taken'])

In [25]:
SETS

(array([False, False, False,  True, False]),
 array([False, False,  True, False, False]),
 array([ True,  True, False, False, False]),
 array([ True, False,  True, False, False]),
 array([False, False,  True, False, False]),
 array([ True, False, False, False, False]),
 array([ True,  True, False, False, False]),
 array([False, False,  True, False, False]),
 array([False, False,  True,  True, False]),
 array([False, False, False, False,  True]))

In [26]:
def goal_check(state):
    return np.all(
        reduce(
            np.logical_or, 
            [SETS[i] for i in state.taken], 
            np.array([False for _ in range(PROBLEM_SIZE)]))
        )

def distance (state):
    return PROBLEM_SIZE - sum(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]))
        )

def heuristic(state):
    return distance(state) + len(state.not_taken)

In [27]:
assert goal_check(
    State(set(range(NUM_SETS)), set())
), "Problem not solvable"

In [31]:
frontier = PriorityQueue()
state = State(set(), set(range(NUM_SETS)))
frontier.put((heuristic(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for action in current_state[1]:
        new_state = State(
            current_state.taken ^ {action},
            current_state.not_taken ^ {action},
        )
        frontier.put((heuristic(new_state), new_state))
    _, current_state = frontier.get()

print(
    f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)"
)

Solved in 3 steps (3 tiles)


In [13]:
current_state

State(taken={0, 2}, not_taken={1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})

In [14]:
SETS[0]

array([False,  True,  True,  True, False])